version: '3.5'

services: 

    nginx:
        image: nginx
        container_name: nginx
        ports:
            - "80:80"
        networks:
            - net
        depends_on:
            - athletes
            - disciplines
            - gateway
            - front
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            
    front:
      build: front
      container_name: front
      ports:
            - "8083:8083"
      networks:
            - net
      depends_on:
            - athletes
            - disciplines
            - gateway
 
    athletes:    
        build: ./athlete
        container_name: athletes
        ports:
            - "8082:8082"
        networks:
            - net
          
    disciplines:   
        build: ./discipline
        container_name: disciplines 
        ports:
            - "8081:8081"        
        networks:
            - net
            
    gateway:   
        build: ./gateway
        ports:
            - "8080:8080"
        networks:
            - net
        depends_on:
            - athletes
            - disciplines

networks:
    net: 